
data = [
    "ybruvapdgixszyckwtfqjonsie",
    "mbruvapxghslyyckwtfqjonsie",
    "mbruvapdghslzyckwtkujonsie",
    "rwruvapdghxlzyckwtfqjcnsie",
    "obruvapdgtxlzyckwtfqionsie",
    "lbruvapdghxqzyckwtfqjfnsie",
    "mbrunapdghxlzyccatfqjonsie",
    "mbruvapdghxlzyokltfqjdnsie",
    "ybruvapdghxlzmckwtfqjmnsie",
    "mbruwaadghxdzyckwtfqjonsie",
    "muruvapdghxlzyckvtfqjonsim",
    "mbruvapdghxlkyckwtxqjonjie",
    "mbruvaqdghxlzyckwtfqjrnnie",
    "mwruvapdghdlzyckttfqjonsie",
    "mbruvapdgtelzyckwxfqjonsie",
    "mbruvapdohxlzvckwtfqjonhie",
    "mbrugapdgbxlzyckwtfqjynsie",
    "mbruvapdghxlzyckwtlqjonjiu",
    "mbruvapwghxlzyckwafqjonbie",
    "wbruvapdghxlhyckwtfqjonsii",
    "mbruvapdghxlzyckwtcqnonsiq",
    "mbyuvapighxlzybkwtfqjonsie",
    "mbrrvapdghxvzyckwtfqjonsio",
    "mhruvapdghrlzyckwtfzjonsie",
    "mtruvapvghxlzyckwtfnjonsie",
    "mmrlhapdghxlzyckwtfqjonsie",
    "mbruvapdgpxlzyjkwtfqjovsie",
    "mbrucapdghxlzymkwtzqjonsie",
    "mbeuvafdghxlzyckwtfqjonwie",
    "mbruvapcghxlayckwtfqjonsii",
    "mbruvabdghxlzyckwtfqyansie",
    "mbruvjpdghxlzyckwtfqgfnsie",
    "lbruvapdghxlzyckwtfqjonriv",
    "mbrupapdghxlzycjwtfqronsie",
    "mbpuvapdthxlzymkwtfqjonsie",
    "mbiuvapdgixlzyckwxfqjonsie",
    "mbruvapdghxyzyckwtfcjonsbe",
    "mbrurapkghxlzyckwtfqjonzie",
    "mbrufapdrhxlzyciwtfqjonsie",
    "mbruvapdghxlzbckwtfqjoisae",
    "ubruhapdghxlzuckwtfqjonsie",
    "mbruvapdjhulzyckwtfqjonshe",
    "mbruwapdgyxlzyckntfqjonsie",
    "mwruvapdghplzyckwtfqjonsme",
    "mbruvapjghtlzyckwtfqgonsie",
    "pbruvapdghhlzyckwtfrjonsie",
    "mbruvgpdihxqzyckwtfqjonsie",
    "mbruvahdohxlzyckwtfijonsie",
    "ibuuvapdghxlzyckwtfqjofsie",
    "mbruvandghxlzyckwtfqjrnxie",
    "mbrjvlpdghxlzyckwgfqjonsie",
    "mbruvapogfxlzyckotfqjonsie",
    "mbruvrpdghxlzyckutfejonsie",
    "mbruvbpdghxlzyhkwtfqjonsip",
    "mbruvapdghxlzyckmnfqjensie",
    "mbruvapdghvlzyckwtfqjowsix",
    "mbruvakdgholzwckwtfqjonsie",
    "mbruvapdghxlzackwtfqconsae",
    "mbruvapdghxlzyqvwtfqjlnsie",
    "mprrvapdgfxlzyckwtfqjonsie",
    "mbrunacdghxlhyckwtfqjonsie",
    "obruvapdgsxlzyckwtfqjonvie",
    "murcvapdghslzyckwtfqjonsie",
    "mbruvapdghxlzyzkwmftjonsie",
    "mbrwvapdgtvlzyckwtfqjonsie",
    "mbxuvapdghxlzqcnwtfqjonsie",
    "mbruvaddghxboyckwtfqjonsie",
    "mhruvwndghxlzyckwtfqjonsie",
    "mbrdvapdghxlzyckwmpqjonsie",
    "mbruvapdgyxlzyckizfqjonsie",
    "mbruvapdghxlzlckwtfqeowsie",
    "mbruvbpdgrxlzyckwtfqjonsxe",
    "mbruqapoghxlzyckwtvqjonsie",
    "mbouhapdghmlzyckwtfqjonsie",
    "mbruvapjghxidyckwtfqjonsie",
    "mbsuvapkghxlkyckwtfqjonsie",
    "mbruvlpdghxlzycrwtfqjonsis",
    "mcrueapdghxlzyckwtfqjynsie",
    "muruvapngbxlzyckwtfqjonsie",
    "mbruvapdghxlzycawtfyjojsie",
    "mbruvbpdghxczyjkwtfqjonsie",
    "ybduvapdghxnzyckwtfqjonsie",
    "mbruvbpdghxlzyckwtfbjousie",
    "mbouvapdghxlzycbwtfqponsie",
    "mbruvaedghplzycgwtfqjonsie",
    "mbrhvapdghxlzyckytfqjgnsie",
    "mbruvapdqbxleyckwtfqjonsie",
    "mbruvapddhhldyckwtfqjonsie",
    "mbruvapdghxlwrckwtfqjondie",
    "mbruvapdmhxlzyckwtfqkonsve",
    "xbbuvapdghxlzyckwtfkjonsie",
    "mbruvapdghxlzyckwcfqjunkie",
    "mbruvapdghxlzyckwtfqxonfib",
    "mbrtvapkghxlzyckwtfqeonsie",
    "mbruvazdghxldymkwtfqjonsie",
    "kbruvapddhxlzfckwtfqjonsie",
    "mbouvapdghxlpyckwtfqjoosie",
    "mbauvapdghxlzyckwtfqjszsie",
    "mbruvapdghtlzyckntfqtonsie",
    "mbruvipdggxlzbckwtfqjonsie",
    "mbruqapdghrlzyckwtfqjznsie",
    "myruvacdghxlzyckwifqjonsie",
    "mbruvapdghxlzuckwtfkjocsie",
    "mwjuvapdghxlzyckwtfqjonsxe",
    "mbruvapxghxlzickwtfqjobsie",
    "mbrupapdghxtlyckwtfqjonsie",
    "meruvapdjjxlzyckwtfqjonsie",
    "mbruvkodghxlzyckwofqjonsie",
    "mbruvapdgexlzyckwtgkjonsie",
    "mbruvapwghxlzyckwtcqjonsiw",
    "mbruvapdghxlzykkwtfqtoxsie",
    "mbruvapdahxlzycgwtfwjonsie",
    "mbruvapdgwxlhyckhtfqjonsie",
    "mbruvapbghxlzycbhmfqjonsie",
    "mbruvapdghxvzyzkwtfqjonsin",
    "mbrcvapdqhxlzyckwyfqjonsie",
    "zbruvaxdghxlzyckwgfqjonsie",
    "mtruvapdghxlilckwtfqjonsie",
    "bbruvapdghxlzyckwtfmjonsxe",
    "mbruvajdghxlzyckwtfqfwnsie",
    "mbruvapdgkxlzyckwtfqionpie",
    "rbruvapdghxlryckwdfqjonsie",
    "mbruvandghxlzyckwmfvjonsie",
    "mbruvahdghxlzeckwtfqjonsme",
    "mbruvnpcghxlzyckwtfqjobsie",
    "mbruvapdghqlzyckwtfbjonsiy",
    "mbruvavdghxlzyckwufqjodsie",
    "mbruvapdghxlzyckwtfzmovsie",
    "mbruvlpdghxuzyckwtfqjoesie",
    "mbruvopdghxlzycwwtfqjansie",
    "obruvapdghglzybkwtfqjonsie",
    "mbpuvlpdghxlcyckwtfqjonsie",
    "mbruvaidghxlzyckwtfmjonoie",
    "mbruvapdihxzzyckwtfqjonsiy",
    "mbquvapdghxlzyckwtfqconsme",
    "mbruvapdghslzyckqtfqjojsie",
    "mbrzdapdghxmzyckwtfqjonsie",
    "mwruvapdghxozyckwtfqjonsxe",
    "muruvapdgfxlzyckwtfqjojsie",
    "wtruvapdghxlzyckvtfqjonsie",
    "mbruvapdghxlzyckysfqjxnsie",
    "mbruvrpdghxczyckktfqjonsie",
    "mbquvapdghxlryckwtfqjonsne",
    "mbruvapdghflzycvwtfqjpnsie",
    "mbruvapughclzyckwtfqjonsin",
    "mbrhvapdghxlpyckwtfqjonsre",
    "mbruvapdgtxlzyckwtfqjoosit",
    "mbrupapnghxhzyckwtfqjonsie",
    "mmvuvapdvhxlzyckwtfqjonsie",
    "mbruvaptghxlzyckwtfqjotsse",
    "mgruvapvghxlzyckwtfqjonsix",
    "mbrupapdghxszyckwtfqjunsie",
    "mbruvkpdghelzyckwtfqjpnsie",
    "mbruvrrdghjlzyckwtfqjonsie",
    "mbruvapdghnlzyckwtfkjonsze",
    "mbruvwpdghxlzyckwtfqhoysie",
    "mbrsvapdfhxlzyckwtfqjobsie",
    "mbruvapdgexezymkwtfqjonsie",
    "ybruvapdghxlzyckwtfqxonsiw",
    "mrruvapdghxdzyckwtfqjossie",
    "mbruvapdghtlzyckwtfqconsiu",
    "mbrpvapdghxlzlckwpfqjonsie",
    "mbruvjpdghslzyckwtfqjjnsie",
    "mhruvapoghxlzyckwtfvjonsie",
    "mbrubqpdghvlzyckwtfqjonsie",
    "mbruvapdghxlzackwtfqconsiw",
    "mbruvapdgnxlzkckwtfqjdnsie",
    "mbrudapgghelzyckwtfqjonsie",
    "mbruvapdghxlzlakwbfqjonsie",
    "mbpuvapdghxlzyckwtuqjonjie",
    "abruvapdghxlzykkwtfqjonzie",
    "mbrupupdghxlsyckwtfqjonsie",
    "mbrsvupdghxlzyckwtfqjonkie",
    "mxruvgpdghxllyckwtfqjonsie",
    "mbrnvapdghxlzycbwtfqfonsie",
    "mbrbxapdghxlzyckttfqjonsie",
    "mbnuvapdghxlzyxkwtmqjonsie",
    "mbrfvapdghjlzickwtfqjonsie",
    "mbhuvupdghxlzyxkwtfqjonsie",
    "mbrcvapdghxluyckwtfqjznsie",
    "mbruvapdghxlzyckwofqjoxsiz",
    "mbrevapdghxloyckwtfqjonnie",
    "mbruvipdghnlzyckwtfqjopsie",
    "mbxxvaptghxlzyckwtfqjonsie",
    "mbruvcpdghxlztckwtjqjonsie",
    "mqruvlpdghxlzyckotfqjonsie",
    "mbruvapdgqxlzyckwtfqjpvsie",
    "mbruvapdgvxlzyjkwtfqjbnsie",
    "mbruvapdghxlgyckwtfqcocsie",
    "mbruvapdghxkwyckwtfqjoqsie",
    "mbrgvavdghxlzyckwxfqjonsie",
    "qbruqapdgvxlzyckwtfqjonsie",
    "mbauvapdghxlzgckwtfqjunsie",
    "mbruvapdgdxluyckwtfqjoosie",
    "mbruvapdghxlzykkwtfqwobsie",
    "mbruvapdghxlzhcnwtfqjonqie",
    "mbruvapdghxlzycbhmfqjonsie",
    "mbruvapdghxluyczwtfqjontie",
    "mbruvapnghxlzyckwnfqjonbie",
    "moruvapdghxlzcckwtfqponsie",
    "mbruvapfgxxlzyckwtfqjunsie",
    "mbruvapdghxlryckvtfejonsie",
    "mbrzvapdghxlzvcbwtfqjonsie",
    "mbruvapdgqxlzyckwcfqjonsce",
    "abruvupdrhxlzyckwtfqjonsie",
    "mbrubaptghxlzyckwtfqjondie",
    "mgruvapdgpxlzyckwtfijonsie",
    "mbruvapdghxczlckwtfujonsie",
    "mbruvapdgmmlzyckwtfqjonsir",
    "mbruvapdhhxltyckwtfdjonsie",
    "mbruvapdghxlzyckwtfdjjnste",
    "mbrdvzpdghxlcyckwtfqjonsie",
    "mbruvapdghxlzyckwtnqbonsim",
    "mbrovapdghxlzyckwtfpjousie",
    "mymuvapdghxlzyjkwtfqjonsie",
    "mbpuvapdghxlzyckwtfljcnsie",
    "mbrxvapdghxlzyclwtfqjonpie",
    "mbrueapdghxlzyckwtfqjopsia",
    "mbruvapdghxlzycdwtfqjbfsie",
    "tbruvavdghxlzyckwtmqjonsie",
    "mbduvapdghxlzyckwrfqjrnsie",
    "mkrsvapughxlzyckwtfqjonsie",
    "mbruvapdghylzyckwtfqtolsie",
    "mgruvapdglxldyckwtfqjonsie",
    "mbrunapdghclzyckwtfqjonsiy",
    "mbruvapdgrxlxyckwtfgjonsie",
    "mbruvapdghxpzbckftfqjonsie",
    "mbruvcpdghxyzyckotfqjonsie",
    "mbruvapdghxlsyckwtfqcqnsie",
    "mbruvapdghxlzzckwtfqjonskf",
    "mbruvppdghxlzfckwtfqjgnsie",
    "mbhuvapdghxlzytkwtfqjonoie",
    "mbruvapdghxlzvrkwtfqjjnsie",
    "mbmuvapdghxuzyckwtfqjonsze",
    "mbruvapdghnlzycnwtfqjonsil",
    "mbruvapdgholzyckitfqjonsia",
    "mbruxapdghxlmyckwtfqbonsie",
    "mbauvapdgholzyckwtfqjolsie",
    "mbruvapdghxlzyckwtfqjotslq",
    "dbrutapdghxlzyckwtfqjonsiv",
    "mbruvapdzhxlyyckwtfbjonsie",
    "mmruaapsghxlzyckwtfqjonsie",
    "mbruvaldgqxqzyckwtfqjonsie",
    "mbruvaodghxdzyjkwtfqjonsie",
    "mbrcmatdghxlzyckwtfqjonsie",
    "mbrqvapdgtxlzycewtfqjonsie",
    "mjruvapdghzlzyckwtfqjonrie",
    "mbruvapdghxopcckwtfqjonsie",
    "mbruvapdghxszycwwtfqjoqsie",
    "mbruvapdgoxezyckwtjqjonsie"
]

n = 0
count2 = 0
count3 = 0
for s in data :
    n = n+1
    print(n,s)
    counts = {}
    for c in s : 
        counts[c] = counts.get(c,0)+1
    has_two = False
    has_three = False
    for x in counts:
        if counts[x] == 2 : has_two = True
        if counts[x] == 3 : has_three = True
    if has_two : count2 += 1
    if has_three : count3 += 1
    print(s,has_two,has_three)
print(count2,count3)
print(count2*count3)

found = False
for s1 in data :
    for s2 in data :
        diffs = 0
        for i in range(len(s1)):
            # print(s1[i],s2[i])
            if s1[i] != s2[i] : 
                pos = i
                diffs +=1
        if diffs == 1 :
            found = True
            ans = s1[0 : pos ] + s1[pos + 1 :]
            break
    if found : break

print(s1, s2)
print(ans)



